name: test 
on:
  push:
  
jobs: 
  test: 
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - uses: ./
      env: 
        SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
        DYNAMIC_VAR: ${{secrets.DYNAMIC_VAR}}
      with:
        who-to-greet: 'jingzhu'
