name: test 
on:
  push:
  
jobs: 
  test: 
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - uses: ./
      with: 
        who-to-greet: '[1,2,3]'
        wp-db-name: 'wordpresstest'
        wp-db-user: 'admin'
