name: test 
on:
  create:
  
jobs: 
  test: 
    runs-on: ubuntu-latest
    steps: 
    - uses: ./
      env: 
        env_url: 'http://localhost:80'
        dynamic_var: 'dddd'
      with:
        who-to-greet: 'jingzhu'
